config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[index new create destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :read, :all

    can :destroy, Post, author_id: user.id
    can :destroy, Comment, author_id: user.id

    return unless user.is? :admin

    can :destroy, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true, length: { maximum: 1000 }
  def as_json(_options = {})
    {
      id:,
      text:,
      author_id:,
      post_id:
    }
  end
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_posts_like_counter

  private

  def update_posts_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :title, presence: true, length: { maximum: 250 }

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def as_json(_options = {})
    {
      id:,
      title:,
      text:,
      author_id:,
      comments_counter:,
      likes_counter:
    }
  end

  after_create :update_posts_counter

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true, length: { maximum: 50 }
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :confirmable, :validatable

  def is?(requested_role)
    role == requested_role.to_s
  end

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def after_confirmation_path_for(_resource_name, _resource)
    root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :bio, :photo) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password, :bio, :photo)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.where(post_id: params[:post_id])
    respond_to do |format|
      format.json { render json: @comments }
    end
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  before_action :authenticate_user!, only: [:create]
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new(author_id: @user.id, text: params[:comment][:text], post_id: @post.id) # assign post_id
    respond_to do |format|
      if @comment.save # check if the comment is saved successfully
        flash[:success] = 'Comment was successfully created.'
        format.html { redirect_to "/users/#{@user.id}/posts/#{@post.id}" }
        format.json { render json: @comment, status: :created }
      else
        flash[:error] = 'Something went wrong.'
        render :new # render the new template again with error messages
        format.json { render json: { error: 'Error: Comment could not be saved' }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    respond_to do |format|
      if comment.destroy
        # Successfully deleted the record
        flash[:success] = 'Comment deleted successfully'
        post.decrement!(:comments_counter)
      else
        # Failed to delete the record
        flash.now[:error] = 'Error: Comment could not be deleted'
      end
      format.html { redirect_to "/users/#{current_user.id}/posts/#{params[:post_id]}" }
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = Like.new(author_id: @user.id, post_id: @post.id)
    if @like.save
      flash[:success] = 'You liked this post!'
    else
      flash[:error] = 'Something went wrong.'
    end
    redirect_to user_post_path(@user.id, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:comments, :author).where(author_id: params[:user_id])
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.includes(:author).find(params[:id])
    @comments = @post.comments
    @like = Like.new
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = Post.new(author_id: @user, title: params[:post][:title], text: params[:post][:text])
    @post.author_id = @user.id
    @post.save
    redirect_to user_posts_path(@user)
  end

  def destroy
    post = Post.find(params[:id])
    Post.find(params[:id]).comments.destroy_all
    Post.find(params[:id]).likes.destroy_all
    user = post.author
    respond_to do |format|
      if post.destroy
        user.decrement!(:posts_counter)
        # Successfully deleted the record
        flash[:success] = 'Post deleted successfully'
        format.html { redirect_to "/users/#{current_user.id}/posts" }
      else
        # Failed to delete the record
        flash.now[:error] = 'Error: Post could not be deleted'
        format.html { render :show }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if request.path == destroy_user_session_path
      sign_out(current_user)
      redirect_to root_path
    else
      @user = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<main>
    <div class="new-comment container">
        <h2>Add a comment</h2>
  <%= form_with model: @comment, url: user_post_comments_path(@post) do |form| %>
    <div class='comment-form'>
      <%= form.text_area :text, required: true, autofocus: true, placeholder: 'Leave a comment', class: "form-input" %>
      <%= form.submit "Comment", class: "form-button button" %>
    </div>
    
  <% end %>
    </div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<main>
    <div class="single-user container">
        <section class="user">
            <img src=<%= @user.photo %> alt="User Photo" class="user-photo">
            <div class="user-detail">
                <h2 class="user-name"><%= @user.name%></h2>
                <h4 class="post-count">Number of posts: <%= @user.posts_counter %> </h4>
            </div>
        </section>
        <hr>
        
        <section class="posts container">
  <h3>All Posts from <%= @user.name %></h3>
  <% @user.posts.includes(comments:[:author]).each do |post| %>
    
      <div class="post">
        <div class="post-content">
        
          <h4><a href="/users/<%=@user.id%>/posts/<%=post.id%>"><%= post.title %></a></h4>
          
          <p><%= truncate(post.text, length: 200) %></p>
          <footer class="post-footer">
          <span class="comment-count">Comments: <%= post.comments_counter %></span>,
          <span class="like-count">Likes: <%= post.likes_counter %></span>
          

        </footer>
        </div>
        
        <div class="comments">
        <h5>Comments</h5>
        <% post.comments.each do |comment| %>
          <div id="single-comment"> 
            <span> <%= comment.author.name %> : <%= comment.text %></span>
          </div>
        <% end %>
      </div>
      </div>
  <% end %>
  <button>More Posts</button>
</section>


    </div>

</main>

app/views/posts/new.html.erb
<main>
    <div class="new-post container">
        <h1>Add New Post</h1>
    <%= form_with model: @post, url: user_posts_path(@user) do |form| %>
      <div class="form-container">
        <%= form.text_field :title, required: true, autofocus: true, class: "form-input" %>
        <%= form.text_area :text, required: true, autofocus: true, class: "form-input" %>
        <%= form.submit "Submit", class: "button" %>
      </div>
      
    <% end %>
    </div>

</main>

app/views/posts/show.html.erb
<main>
    <div class="single-post container">
        <header class="post-header">
        <h1 id="post-title">
            <%= @post.title%> by <%= @post.author.name%>
        </h1>
        <div class="post-meta">
            <span>Comments: <%= @post.comments_counter%>, </span>
            <span class="likes">Likes: <%= @post.likes_counter%></span>
            
 
        </div>
        </header>
        <hr>
        <div class="post-body">
        <%= @post.text%>
        </div>
        <hr style="width:66%; min-width: 300px;">
        <footer class="post-footer">
        <div class="post-interactions">
            <%= form_with model: @like, url: user_post_likes_path(1, @post), scope: :like do |form|%>
                <%= form.submit 'Like post', class: 'button' %>
            <% end %>
            <%= link_to "Comment", new_user_post_comment_path( post_id: @post.id), { class: "button" } %>
            <% if can? :destroy , @post %>
        <%= form_with model: @post, method: :delete, local: true, url: "/users/#{@post.author.id}/posts/#{@post.id}/",
          html: {class: "delete-btn"} do |f| %>
          <%= f.submit "Delete Post", class: "button" %>
          <% end %>
      <% end %>
        </div>
        <div class="comments">
                <h5>Comments</h5>
                <% @comments=Post.find(@post.id).comments %>
                    <% @comments.includes(:author).each do |comment| %>
                        <%= render partial: "shared/comment", locals: { user: comment.author,
            comment: comment}  %>
                    <% end %>
            </div>
        </footer>
    </div>
</main>

app/views/shared/_comment.html.erb
<div  class="single-comment">
    <span> <%= comment.author.name %> : <%= comment.text %></span>
    <% if can? :destroy , comment %>
        <%= form_with model: comment, method: :delete, local: true, 
            url: "/users/#{@post.author.id}/posts/#{@post.id}/comments/#{comment.id}/",
            html: {class: "delete-btn"} do |f| %>
                <%= f.submit "Delete", class: "button" %>
            <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<main>
<div class="users container">
<!--
<% if user_signed_in? %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_user_session_path %>
<% end %> -->
    <h1>Users</h1>
    <% @users.each do |user| %>
        <div class="user">
            <img src=<%= user.photo %> alt="User Photo" class="user-photo">
            <div class="user-detail">
                <h2 class="user-name"><a href="/users/<%= user.id %>"><%= user.name%></a></h2>
                <h4 class="post-count">Number of posts: <%= user.posts_counter %> </h4>
            </div>

        </div>
    <% end %>
</div>
</main>

app/views/users/show.html.erb
<main>
    <div class="single-user container">
    <!--
<% if user_signed_in? %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_user_session_path %>
<% end %> -->

        <section class="user">
            <img src=<%= @user.photo %> alt="User Photo" class="user-photo">
            <div class="user-detail">
                <h2 class="user-name"><%= @user.name%></h2>
                <h4 class="post-count">Number of posts: <%= @user.posts_counter %> </h4>
            </div>
        </section>
        <hr>
        <section class="bio">
            <h3>Bio</h3>
            <p><%= @user.bio %></p>
        <section>
        <hr>
        <section class="posts container">
            <h3>Recent Posts</h3>
            <div class="posts">
            <% @user.most_recent_posts.each do |post| %>
            
                <div class="post">
                    <div class="post-content">
                        <h4><a href="<%=@user.id%>/posts/<%=post.id%>"><%= post.title %></a></h4>
                        <p><%= truncate(post.text, length: 200) %></p>
                    </div>
                    <footer class="post-footer">
                    <span class="comment-count">Comments: <%= post.comments_counter %></span>, <span class="like-count">Likes: <%= post.likes_counter %></span>
                   
                    </footer>
                    </div>
               
                
                
            <% end %>
            </div>
            <a href="<%=@user.id%>/posts/" class="button">View all posts</a>
        </section>
    </div>

</main>